receipts_path: "receipt/media/txt"

sum_keys:
  - sum
  - total
  - grand total
  - Grand Total

tax_keys:
  - TAX
  - tax
  - Tax
  - GST
  - CGST
  - SGST

sum_format: '\d+(\.\d+){0,}'

date_format: '([0-9]{1,2}[./\-\ ][0-9]{1,2}[./\ -][0-9]{2,4})|([0-9]{1,2}[./\-\ ][a-zA-Z]{3,}[./\ -][0-9]{2,4})'

tax_format: '\d+(\.\d+){0,}'

